#!/usr/bin/env python3
# ================================================================
# File: packer/scripts/render_local_vars.py
# Purpose:
#   Render the local untracked Packer variable file from homelab state
#   and secret material.
#
# Notes:
#   - This script follows the existing repo pattern of sourcing state under
#     state/configs and state/secrets.
#   - Output is written to packer/proxmox/local.auto.pkrvars.hcl.
# ================================================================
from __future__ import annotations

import subprocess
import os
import secrets
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[2]
STATE_DIR = ROOT_DIR / "state"
CONFIG_ENV = STATE_DIR / "configs" / ".env"
PROXMOX_TOKEN_ENV = STATE_DIR / "secrets" / "proxmox" / "proxmox-api-token.env"
PACKER_SECRET_ENV = STATE_DIR / "secrets" / "packer" / "packer-build.env"
OUTPUT_FILE = ROOT_DIR / "packer" / "proxmox" / "local.auto.pkrvars.hcl"


def read_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        raise FileNotFoundError(f"Required env file not found: {path}")
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def ensure_packer_secret() -> dict[str, str]:
    PACKER_SECRET_ENV.parent.mkdir(parents=True, exist_ok=True)
    if PACKER_SECRET_ENV.exists():
        return read_env_file(PACKER_SECRET_ENV)

    password = secrets.token_urlsafe(18)
    ssh_pub_path = Path.home() / ".ssh" / "id_ed25519.pub"
    content = (
        "# ================================================================\n"
        "# File: state/secrets/packer/packer-build.env\n"
        "# Purpose:\n"
        "#   Local-only Packer guest build credentials and defaults.\n"
        "# ================================================================\n"
        f"PACKER_ADMIN_PASSWORD={password}\n"
        f"PACKER_SSH_PUBLIC_KEY_PATH={ssh_pub_path}\n"
    )
    PACKER_SECRET_ENV.write_text(content, encoding="utf-8")
    os.chmod(PACKER_SECRET_ENV, 0o600)
    return read_env_file(PACKER_SECRET_ENV)


def hcl_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


if __name__ == "__main__":
    config = read_env_file(CONFIG_ENV)
    token = read_env_file(PROXMOX_TOKEN_ENV)
    packer_secret = ensure_packer_secret()

    admin_password = packer_secret["PACKER_ADMIN_PASSWORD"]
    result = subprocess.run(["openssl", "passwd", "-6", "-salt", secrets.token_hex(8), admin_password], check=True, capture_output=True, text=True)
    password_hash = result.stdout.strip()

    ssh_pub_path = Path(packer_secret.get("PACKER_SSH_PUBLIC_KEY_PATH", str(Path.home() / ".ssh" / "id_ed25519.pub"))).expanduser()
    if not ssh_pub_path.exists():
        raise FileNotFoundError(f"SSH public key not found: {ssh_pub_path}")
    ssh_public_key = ssh_pub_path.read_text(encoding="utf-8").strip()

    proxmox_host = config.get("PROXMOX_HOST_IP", config.get("PROXMOX_HOST", "192.168.88.250"))
    proxmox_url = f"https://{proxmox_host}:8006/api2/json"

    lines = [
        "# ================================================================",
        "# File: packer/proxmox/local.auto.pkrvars.hcl",
        "# Purpose:",
        "#   Local-only rendered values for Packer Proxmox template builds.",
        "#",
        "# Notes:",
        "#   - Generated by packer/scripts/render_local_vars.py.",
        "#   - Keep this file uncommitted.",
        "# ================================================================",
        f"proxmox_url = {hcl_string(proxmox_url)}",
        f"proxmox_node = {hcl_string(config.get('PROXMOX_NODE_NAME', config.get('PROXMOX_HOST', 'pve01')))}",
        f"proxmox_api_token_name = {hcl_string(token['PROXMOX_API_TOKEN_NAME'])}",
        f"proxmox_api_token_value = {hcl_string(token['PROXMOX_API_TOKEN_VALUE'])}",
        f"insecure_skip_tls_verify = {config.get('PROXMOX_INSECURE_TLS', 'true').lower()}",
        f"proxmox_iso_storage = {hcl_string(config.get('PROXMOX_TEMPLATE_DATASTORE', 'local'))}",
        f"proxmox_vm_storage = {hcl_string(config.get('PROXMOX_VM_DATASTORE', 'local-lvm'))}",
        f"proxmox_cloud_init_storage = {hcl_string(config.get('PROXMOX_SNIPPETS_DATASTORE', 'local'))}",
        f"proxmox_bridge = {hcl_string(config.get('PROXMOX_BRIDGE', 'vmbr0'))}",
        f"admin_username = {hcl_string('fouchger')}",
        f"admin_password = {hcl_string(admin_password)}",
        f"admin_password_hash = {hcl_string(password_hash)}",
        f"ssh_public_key = {hcl_string(ssh_public_key)}",
        f"timezone = {hcl_string('Pacific/Auckland')}",
        f"locale = {hcl_string('en_NZ.UTF-8')}",
        f"keyboard_layout = {hcl_string('us')}",
    ]

    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(OUTPUT_FILE, 0o600)
    print(f"Rendered {OUTPUT_FILE}")
